basePath: /
host: localhost:8080
info:
  contact:
    name: Aaron Saikovski
  description: A random lottery generator API using Go & Fiber
  license:
    name: MIT
  title: golotteryservice
  version: "0.1"
paths:
  /lottery:
    get:
      consumes:
      - '*/*'
      description: 'Generates the lottery numbers and returns JSON - The request responds
        to a url matching:  /lottery?maxgames=XX&randnum=XX&maxnumspergame=XX'
      produces:
      - text/plain
      responses:
        "200":
          description: OK
      summary: Lottery number generator
      tags:
      - Lottery
  /ping:
    get:
      consumes:
      - '*/*'
      description: get the status of server.
      produces:
      - text/plain
      responses:
        "200":
          description: OK
      summary: Show the status of server - Ping/Pong
      tags:
      - health
swagger: "2.0"
